### ISSUE TITLE
Add Balancing switch request

### ISSUE THREAD

**Issue by leodesigner** [syssi/esphome-daly-bms#25]
Hi,

Thank you for your work @syssi !
Just got this project working with Daly Balancer. (not BMS)
The only missing feature is Balancer turn on/off switch.
I cannot find it in the modbus registers unfortunately :(

Any suggestions where to look? Snoop BLE HCI communication ?

**Comment by syssi** [comment]
Could you prepare a btsnoop capture using the Android app?

**Comment by leodesigner** [comment]
> https://www.dalybms.com/download-pc-software/

The link to the balancer used: 
https://www.dalybms.com/active-balancer-lifepo4-16s-daly-3-to-24s-1a-smart-active-balancer-product/

Looks like these are responsible:

Balancer BT logs

Value: d20600cf0000aa56
Value: d20600cf00016b96

00cf register

I will test today.

**Comment by syssi** [comment]
Could you provide the complete btsnoop capture? It can be easily anonymized. I would like to add it to the project.

**Comment by leodesigner** [comment]
Not sure how to anonymise it. There is a lot of other devices and I was specifically targeting balancer on/off switch. 
The other datapoints (cell voltages, temperature) are captured perfectly, except delta cell voltage needs correction.
It shows 0.0007 V instead of 0.007 V.

**Comment by syssi** [comment]
I've added the new switch entity. Please give it a try by changing the `external_components_source` to the feature branch `@add-balancer-switch`:

```
substitutions:
  name: daly-bms-ble
  device_description: "Monitor a DALY Battery Management System via BLE"
  external_components_source: github://syssi/esphome-daly-bms@add-balancer-switch
```
