### ISSUE TITLE
Update switch states

### ISSUE THREAD

**Issue by felipecrs** [syssi/esphome-daly-bms#28]
This was initially discussed [here](https://github.com/syssi/esphome-daly-bms/issues/25#issuecomment-2461733057) and decided to create a dedicated issue for it. 

In my opinion, it would be great if the switch state would copy the state of their counterpart binary sensors, even if they could be some seconds outdated.

When turning on the switch, assume state is true until the next read. The same for `switch.turn_off`.

**Comment by syssi** [comment]
This feature is ready. @felipecrs Could you update your YAML configuration to:

```
substitutions:
  name: daly-bms-ble
  device_description: "Monitor a DALY Battery Management System via BLE"
  external_components_source: github://syssi/esphome-daly-bms@add-command-queue
```

and verify the settings registers get retrieved now? A ESPHome log would be nice too.
